### ISSUE TITLE
Translate Plugin

### ISSUE THREAD

**Issue by jairockman** [tomolimo/officeonline#14]
Is there any group where we can join to help to translate the plugin?

**Comment by tomolimo** [comment]
Hello @jcervantes-sipecom 
I'm going to provide a translation project on CrowdIn (I've sent a request to them to be able to create a translation project for opensource project).
I'll keep you informed.
Thank you,
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Hello @jcervantes-sipecom 
Here is the link to crowdin translation tool: https://crowdin.com/project/officeonline/invite?h=94826c918235da07bc134c9b73311ba91805293
You should ask me for the langages you want to add.
Thank you,
Regards,
Tomolimo

**Comment by jairockman** [comment]
Thank you @tomolimo, the language is: es_EC (Español Ecuador) thanks.

**Comment by tomolimo** [comment]
Hello @jcervantes-sipecom 
I've added es_ES and es_EC
thank you
regards,
Tomolimo

**Comment by jairockman** [comment]
Thank you @tomolimo, already translated.
