### ISSUE TITLE
Configuration OfficeOnline

### ISSUE THREAD

**Issue by ekip-94** [tomolimo/officeonline#2]
Can someone help me w/ the configration of OfficeOnline cuz I don't know how to configure it .
Thx for help guys

**Comment by tomolimo** [comment]
Hello @aze789 ,

You just need to set the URL of your Office Online Server, and the Net zone you want to use:
![image](https://user-images.githubusercontent.com/7569958/40729208-2df58ad2-642c-11e8-8834-03c954bbe2ed.png)

regards,
Tomolimo

**Comment by ekip-94** [comment]
Thx man but my entreprise don't have Office Online Server do you know if it's possible to use it with Office 365 ?

**Comment by tomolimo** [comment]
Hello @aze789 
May be the answer to your question is: 
https://stackoverflow.com/questions/39772584/wopi-host-not-called/39789525#39789525
regards,
Tomolimo

**Comment by ekip-94** [comment]
thx for you answer :)

**Comment by tomolimo** [comment]
you're welcome
