### ISSUE TITLE
Add the option to edit or view documents directy from task or tickets

### ISSUE THREAD

**Issue by jairockman** [tomolimo/officeonline#25]
Hi, first of all, thank you for this plugin, it's very good and help to view or edit document directly from GLPI using Office Online Server.

A thing to add, is the possibility of the option to view/edit document attachment directly from tickets, tasks, etc., actually it's just only possible in Document option in GLPI:

 ![image](https://github.com/tomolimo/officeonline/assets/56606032/91f05143-60dd-46e8-b688-3b2da5be28a6)

![image](https://github.com/tomolimo/officeonline/assets/56606032/2ba14f8e-9fbb-43c3-919b-9428fbb43ee1)

If I clic in a document attached in a task, ticket, etc., this download the document, instead of opening it in the plugin. And if I clic in Edit, it open the document ID page:

![image](https://github.com/tomolimo/officeonline/assets/56606032/b9039a80-21ab-4cec-86c5-c921448f0888)

**Comment by tomolimo** [comment]
Hello @jcervantes-sipecom 
Which version of GLPI, which version of OfficeOnline plugin?
Do you have error in logs?
Do you have errors in Javascript console (press F12 to open dev tools, and then refresh page)?
Which current profile (central or helpdesk) are you using?
Thank you
Regards,
Tomolimo

**Comment by jairockman** [comment]
Hi, @tomolimo 

Which version of GLPI, which version of OfficeOnline plugin? GLPI: 10.0.11 and plugin 3.0.1

Do you have error in logs? No, none

Do you have errors in Javascript console (press F12 to open dev tools, and then refresh page)? I don't know exactly where view Javascript error, but I got this one only:

![image](https://github.com/tomolimo/officeonline/assets/56606032/1c0ffc7c-7fa5-49ad-95dc-53af536163d9)


Which current profile (central or helpdesk) are you using? Super-Admin Central

I found a weird situation, this happen with .xlsx files, not with .docx, or maybe it's something with the length of the filename or the width of the follow-up or task that document is attached? :

File .xlsx:

![image](https://github.com/tomolimo/officeonline/assets/56606032/3ea7a764-cad9-421e-b097-6ac77c46886a)


File .docx:

![image](https://github.com/tomolimo/officeonline/assets/56606032/1d2c11df-2dce-4d32-8803-cd3282140ec1)

**Comment by jairockman** [comment]
Hi @tomolimo, 

Yes, it looks like something with the length of the filename:

![image](https://github.com/tomolimo/officeonline/assets/56606032/77f9fdbd-bb2f-47a4-ae4c-28d5957d4136)

**Comment by tomolimo** [comment]
Hello @jcervantes-sipecom 
Could you try release 3.0.2?
https://github.com/tomolimo/officeonline/releases/tag/3.0.2
Thank you,
Regards,
Tomolimo

**Comment by jairockman** [comment]
Hi @tomolimo, no now I can't edit any long length filename file:

![image](https://github.com/tomolimo/officeonline/assets/56606032/1862e884-b85a-4b4f-a8c8-6542f65b7f4a)

![image](https://github.com/tomolimo/officeonline/assets/56606032/3b3d8fd1-67a8-4f27-9e84-b36002aaec2b)

**Comment by tomolimo** [comment]
Hello @jcervantes-sipecom 
Where did you get this screencopy?
![image](https://github.com/tomolimo/officeonline/assets/7569958/529128e8-e9ec-44a6-b8fa-42272a3d0027)

Thank you
Regards,
Tomolimo

**Comment by jairockman** [comment]
Hi @tomolimo ,

From /front/document.php

**Comment by tomolimo** [comment]
Ok, thank you,
I see, it's coming from the filter I've added...
I'll fix that ASAP

**Comment by tomolimo** [comment]
Hello @jcervantes-sipecom
Could you try release 3.0.3?
https://github.com/tomolimo/officeonline/releases/tag/3.0.3
Thank you,
Regards,
Tomolimo

**Comment by jairockman** [comment]
Hi @tomolimo,

Yes now, in /front/document.php appears correctly:

![image](https://github.com/tomolimo/officeonline/assets/56606032/81b77225-9c30-46be-a181-8e066c342acb)

But in Tickets or task doesn't:

It's looks like something with the zoom/screen resolution and filename, so the link to Office Online doesn't show-up:

 - My Screen Resolution:

![image](https://github.com/tomolimo/officeonline/assets/56606032/f0b5a598-216a-46ec-ab54-80bab8efcf0e)


 - Browser at 100%
 
![image](https://github.com/tomolimo/officeonline/assets/56606032/1a74b920-34b5-450d-b1e7-e467a656fd13)

- Browser at 75% or adjusting the filename to show up completely

![image](https://github.com/tomolimo/officeonline/assets/56606032/ac53994b-cbe8-4c10-8c74-8530a8f92d9c)

**Comment by tomolimo** [comment]
Hello @jcervantes-sipecom 
All these should be solved by https://github.com/tomolimo/officeonline/releases/tag/3.1.0
Thank you,
Regards,
Tomolimo

**Comment by jairockman** [comment]
Hi @tomolimo thank you, yes I confirm:

- Ticket / Tasks

![image](https://github.com/tomolimo/officeonline/assets/56606032/e783ba0f-a0af-47fe-90a3-a50247f0847a)

- /documents

![image](https://github.com/tomolimo/officeonline/assets/56606032/c819bf04-47f0-43f8-a4c9-1726d077cb67)
