### ISSUE TITLE
GLPI 9.5 Compatibility

### ISSUE THREAD

**Issue by GalactikDrkCoder** [tomolimo/officeonline#9]
Bonjour,
Je viens de découvrir ce plugin qui m'interesse fortement. Cependant je suis en version 9.5.2 de GLPI.

Bon courage

**Comment by tomolimo** [comment]
Hello @JarJar025 
We are going to start on the migration of this plugin in the next weeks
Thank you
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Fixed by https://github.com/tomolimo/officeonline/releases/tag/2.0.2
